kind: Service
apiVersion: v1
metadata:
  name: spring3hibernate-service
  namespace: t0
  labels:
    app: spring3hibernate
    version: "1.0"
    environment: testing
spec:
  selector:
    app: spring3hibernate
    version: "1.0"
    environment: testing
  type: LoadBalancer
  ports:
    - port: 8080
  externalIPs:
    - 192.168.56.141
    - 192.168.56.142
    - 192.168.56.143
